# Generated by Django 6.0.2 on 2026-03-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensereport_expenseitem_invoice_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales'), ('structure', 'Project - Structure'), ('electrical', 'Project - Electrical'), ('services', 'Services'), ('materials', 'Materials')], max_length=50),
        ),
    ]
