# Generated by Django 6.0.2 on 2026-03-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_projectcosting_entered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='receipt',
        ),
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expense_receipts/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.expensereport')),
            ],
        ),
    ]
