# Generated by Django 6.0.2 on 2026-03-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_expenseitem_receipt_expensereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
