# Generated by Django 6.0.2 on 2026-03-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rename_estimated_cost_projectcosting_system_costing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcosting',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='design_costs/'),
        ),
    ]
