# Generated by Django 6.0.2 on 2026-03-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_designcosting_design_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcosting',
            name='client_approved',
            field=models.BooleanField(default=False),
        ),
    ]
