# Generated by Django 6.0.2 on 2026-03-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_projectcosting_client_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcosting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcosting',
            name='proposal_sent',
            field=models.BooleanField(default=False),
        ),
    ]
