# Generated by Django 6.0.2 on 2026-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_projectcosting_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcosting',
            name='kseb_cost',
            field=models.FloatField(default=0),
        ),
    ]
