# Generated by Django 6.0.2 on 2026-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_projectcosting_kseb_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcosting',
            name='kseb_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
