# Generated by Django 6.0.2 on 2026-10-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_expensereport_submitted_by'),
        ('projects', '0032_assetwarranty_historicalassetwarranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('booking', 'Booking / Advance'), ('dispatch', 'Material Dispatch'), ('installation', 'Installation Completion'), ('commissioning', 'Commissioning & Net-Metering'), ('final', 'Final Payment')], max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='e.g. 50.00 for 50%', max_digits=5)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('payment_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
    ]
