# Generated by Django 6.0 on 2026-02-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
