# Generated by Django 6.0.2 on 2026-03-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_delete_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('service', models.CharField(choices=[('', 'Select Service'), ('ongrid', 'On-grid Solar'), ('offgrid', 'Off-grid Solar'), ('hybrid', 'Hybrid Solar'), ('leakproof', 'Leakproof Solar Roof'), ('commercial', 'Commercial Solar')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('converted', 'Converted to Project'), ('rejected', 'Rejected')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
