# Generated by Django 6.0.2 on 2026-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_lead_updated_at_alter_lead_email_alter_lead_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
