# Generated by Django 6.0.2 on 2026-03-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_lead_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='note',
            new_name='notes',
        ),
    ]
