# Generated by Django 6.0.2 on 2026-03-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_lead'),
        ('public', '0014_lead_assigned_to_lead_follow_up_date_lead_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
