# Generated by Django 6.0.2 on 2026-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('panel', 'Solar Panel'), ('inverter', 'Inverter'), ('battery', 'Battery'), ('cable', 'Cable'), ('structure', 'Structure'), ('accessory', 'Accessory')], max_length=100, null=True),
        ),
    ]
