# Generated by Django 6.0.2 on 2026-03-12 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_material_category'),
        ('projects', '0007_remove_project_gallery_projectimage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceived',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_received', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='materialallocation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.material'),
        ),
        migrations.AlterField(
            model_name='materialallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='procurement.material'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='procurement.material'),
        ),
        migrations.AlterUniqueTogether(
            name='materialallocation',
            unique_together={('project', 'material')},
        ),
    ]
