# Generated by Django 6.0.2 on 2026-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_material_brand_alter_goodsreceived_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialallocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
