# Generated by Django 6.0.2 on 2026-03-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_materialallocation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialallocation',
            unique_together=set(),
        ),
    ]
