# Generated by Django 6.0.2 on 2026-04-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_materialallocation_allocated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
