# Generated by Django 6.0 on 2026-02-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.engineerprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='projects.projectimage'),
        ),
    ]
