# Generated by Django 6.0.2 on 2026-03-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('public', '0009_lead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='public.lead'),
        ),
        migrations.AddField(
            model_name='project',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('ongrid', 'On-grid Solar'), ('offgrid', 'Off-grid Solar'), ('hybrid', 'Hybrid Solar'), ('leakproof', 'Leakproof Solar Roof'), ('commercial', 'Commercial Solar')], default='leakproof', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('site_visit', 'Site Visit & Feasibility Study'), ('design_prep', 'Design Preparation'), ('design_approval', 'Design Approval'), ('design_costing', 'Design Costing'), ('costing_approval', 'Costing Approval'), ('structure', 'Structure Installation'), ('electrical', 'Electrical Work'), ('licensing', 'Licensing'), ('energisation', 'Energisation'), ('completed', 'Completed')], default='lead', max_length=50),
        ),
    ]
