# Generated by Django 6.0.2 on 2026-03-07 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_lead'),
        ('users', '0004_remove_employee_address_remove_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
    ]
