# Generated by Django 6.0.2 on 2026-03-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_image_projectactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project'),
        ),
    ]
