# Generated by Django 6.0.2 on 2026-03-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task'),
        ('users', '0009_alter_employee_designation_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.employee'),
        ),
    ]
