# Generated by Django 6.0.2 on 2026-03-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectdesigndocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdesigndocument',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
