# Generated by Django 6.0.2 on 2026-03-21 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_installationissue_installationphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Summary'), ('completion', 'Work Completion')], default='daily', max_length=20)),
                ('work_type', models.CharField(choices=[('panel', 'Panel Installation'), ('inverter', 'Inverter Setup'), ('wiring', 'Wiring'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='reports/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='reports/after/')),
                ('issues', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
