# Generated by Django 6.0.2 on 2026-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_workreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesigndocument',
            name='discussion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdesigndocument',
            name='needs_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectdesigndocument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
