# Generated by Django 6.0.2 on 2026-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectdesigndocument_discussion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installationtask',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='new', max_length=20),
        ),
    ]
