# Generated by Django 6.0.2 on 2026-03-26 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_review_is_approved'),
        ('projects', '0019_installationtask_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('before_photo', 'Before Photo (Site Visit / Before Work)'), ('after_photo', 'After Photo (Installation / Service Completion)'), ('design_document', 'Design Document'), ('installation_photo', 'Installation Progress Photo'), ('issue_photo', 'Issue Photo'), ('service_report_photo', 'Service Report Photo')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('installation_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.installationtask')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.installationissue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project')),
                ('service_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.servicereport')),
                ('site_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.sitephoto')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.workreport')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='InstallationPhoto',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
