# Generated by Django 6.0.2 on 2026-03-27 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_projectimage_project_projectmedia_and_more'),
        ('users', '0009_alter_employee_designation_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationtask',
            name='step',
            field=models.CharField(choices=[('site_inspection', 'Site Inspection Completed'), ('structure_fixing', 'Mounting Structure Fixed'), ('panel_mounting', 'Solar Panels Mounted'), ('wiring', 'DC & AC Wiring Completed'), ('inverter', 'Inverter Installed & Connected'), ('testing', 'System Testing ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('feasibility', 'Feasibility Study'), ('design_prep', 'Design Preparation'), ('design_approval', 'Design Approval'), ('design_costing', 'Design Costing'), ('costing_approval', 'Costing Approval'), ('structure', 'Structure Installation'), ('electrical', 'Electrical Work'), ('licensing', 'Licensing'), ('energisation', 'Energisation'), ('completed', 'Completed')], default='lead', max_length=50),
        ),
        migrations.CreateModel(
            name='FeasibilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=50)),
                ('roof_type', models.CharField(choices=[('rcc', 'RCC'), ('metal', 'Metal'), ('tile', 'Tile')], max_length=50)),
                ('roof_area', models.FloatField(help_text='Area in sq.ft')),
                ('location_notes', models.TextField(blank=True)),
                ('structure_feasibility', models.BooleanField(default=True)),
                ('mounting_feasibility_notes', models.TextField(blank=True)),
                ('accessibility_for_maintenance', models.BooleanField(default=True)),
                ('shadow_analysis', models.CharField(choices=[('none', 'No Shading'), ('partial', 'Partial Shading'), ('heavy', 'Heavy Shading')], max_length=50)),
                ('orientation', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], max_length=20)),
                ('connection_type', models.CharField(choices=[('single_phase', 'Single Phase'), ('three_phase', 'Three Phase')], max_length=20)),
                ('monthly_consumption', models.IntegerField(blank=True, null=True)),
                ('suggested_capacity', models.FloatField(help_text='kW')),
                ('system_type', models.CharField(choices=[('on_grid', 'On-Grid'), ('off_grid', 'Off-Grid'), ('hybrid', 'Hybrid')], max_length=20)),
                ('inverter_type', models.CharField(blank=True, max_length=100)),
                ('special_design_notes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_feasibilities', to='users.employee')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility', to='projects.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_reports', to='users.employee')),
            ],
        ),
    ]
