# Generated by Django 6.0.2 on 2026-03-27 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_installationtask_step_alter_project_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feasibilityreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_feasibilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feasibilityreport',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
