# Generated by Django 6.0.2 on 2026-03-29 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_installationtask_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('customer_info', 'Customer Information Collection'), ('mnre_registration', 'MNRE Registration'), ('annex1_submission', 'KSEB Annex I Submission'), ('equipment_info', 'Equipment Information Collection'), ('agreement_prep', 'Agreement Preparation'), ('final_docs', 'Final Document Preparation'), ('annex2_submission', 'KSEB Annex II Submission'), ('annex3_submission', 'KSEB Annex III Submission'), ('mnre_final', 'MNRE Final Submission'), ('subsidy_credit', 'Subsidy Credit')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensing_tasks', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('project', 'step')},
            },
        ),
        migrations.CreateModel(
            name='LicensingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='licensing_docs/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.licensingtask')),
            ],
        ),
    ]
