# Generated by Django 6.0.2 on 2026-03-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_licensingtask_licensingdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='licensingdocument',
            name='document_type',
            field=models.CharField(choices=[('annex1', 'Annex I'), ('annex2', 'Annex II'), ('annex3', 'Annex III'), ('agreement', 'Agreement'), ('mnre', 'MNRE Document'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='licensingdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licensingtask',
            name='phase',
            field=models.CharField(choices=[('preparation', 'Preparation'), ('kseb', 'KSEB Processing'), ('mnre', 'MNRE Processing'), ('subsidy', 'Subsidy & Closure')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='licensingtask',
            name='step',
            field=models.CharField(choices=[('customer_info', 'Customer Info Collection'), ('mnre_registration', 'MNRE Registration'), ('annex1', 'KSEB Annex I Submission'), ('equipment_info', 'Equipment Info Collection'), ('agreement', 'Agreement Preparation'), ('annex2', 'KSEB Annex II Submission'), ('annex3', 'KSEB Annex III Submission'), ('mnre_final', 'MNRE Final Submission'), ('subsidy', 'Subsidy Credit')], max_length=50),
        ),
    ]
