# Generated by Django 6.0.2 on 2026-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_remove_project_slug_licensingdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationtask',
            name='step',
            field=models.CharField(choices=[('site_inspection', 'Site Inspection Completed'), ('structure_fixing', 'Mounting Structure Fixed'), ('panel_mounting', 'Solar Panels Mounted'), ('wiring', 'DC & AC Wiring Completed'), ('testing', 'System Testing ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='category',
            field=models.CharField(choices=[('before_photo', 'Before Media (Photo / Video)'), ('after_photo', 'After Media (Photo / Video)'), ('design_document', 'Design File'), ('installation_photo', 'Installation Media'), ('issue_photo', 'Issue Media'), ('service_report_photo', 'Service Report Media')], max_length=50),
        ),
    ]
