# Generated by Django 6.0.2 on 2026-04-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_installationtask_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibilityreport',
            name='location_notes',
        ),
        migrations.RemoveField(
            model_name='feasibilityreport',
            name='mounting_feasibility_notes',
        ),
        migrations.RemoveField(
            model_name='feasibilityreport',
            name='special_design_notes',
        ),
    ]
