# Generated by Django 6.0.2 on 2026-10-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_feasibilityreport_location_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='revenue',
        ),
    ]
