# Generated by Django 6.0.2 on 2026-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('feasibility', 'Feasibility Study'), ('design_prep', 'Design Preparation'), ('design_approval', 'Design Approval'), ('design_costing', 'Design Costing'), ('costing_approval', 'Costing Approval'), ('quotation', 'Quotation & Approval'), ('order', 'Order Confirmed'), ('payment', 'Payment & Loan Approval'), ('procurement', 'Procurement & Inventory'), ('structure', 'Structure Installation'), ('electrical', 'Electrical Work'), ('qc', 'Quality Control (QC)'), ('licensing', 'Licensing'), ('net_metering', 'Net Metering'), ('subsidy', 'Subsidy Processing'), ('energisation', 'Energisation & Commissioning'), ('handover', 'Handover'), ('completed', 'Completed'), ('amc', 'AMC / O&M')], default='lead', max_length=50),
        ),
    ]
