# Generated by Django 6.0.2 on 2026-03-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_leadactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
