# Generated by Django 6.0.2 on 2026-03-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
