# Generated by Django 6.0.2 on 2026-03-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_latitude_lead_location_lead_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='longitude',
        ),
    ]
