# Generated by Django 6.0.2 on 2026-03-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_leadactivity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_done',
            field=models.BooleanField(default=False),
        ),
    ]
