# Generated by Django 6.0.2 on 2026-03-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_follow_up_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
