# Generated by Django 6.0.2 on 2026-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_follow_up_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='site_visit_completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='site_visit_done',
            field=models.BooleanField(default=False),
        ),
    ]
