# Generated by Django 6.0.2 on 2026-03-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_sitephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
    ]
