# Generated by Django 6.0.2 on 2026-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_review_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadactivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='description',
            field=models.TextField(),
        ),
    ]
