# Generated by Django 6.0.2 on 2026-03-04 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountantprofile',
            old_name='is_active_employee',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='engineerprofile',
            old_name='is_active_employee',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='is_active_employee',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountantprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employees'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employees'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employees'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='employees')),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('designation', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
