# Generated by Django 6.0.2 on 2026-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_active_employee_accountantprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountantprofile',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
