# Generated by Django 6.0.2 on 2026-03-07 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_engineer'),
        ('users', '0004_remove_employee_address_remove_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='access_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employees'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'engineer']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccountantProfile',
        ),
        migrations.DeleteModel(
            name='EngineerProfile',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
