# Generated by Django 6.0.2 on 2026-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_category_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('accountant', 'Accountant'), ('sales', 'Sales'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
