# Generated by Django 6.0.2 on 2026-03-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employee_designation_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('accountant', 'Accountant'), ('sales', 'Sales'), ('staff', 'Staff'), ('liaison', 'Liaison Officer')], default='staff', max_length=10),
        ),
    ]
