# Generated by Django 6.0.2 on 2026-10-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_employee_id_employeeexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('target_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('achieved_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leads_assigned', models.IntegerField(default=0)),
                ('leads_converted', models.IntegerField(default=0)),
                ('projects_completed_on_time', models.IntegerField(default=0)),
                ('projects_delayed', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='users.employee')),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
